### ISSUE TITLE
[Meta] Create Replacement Assets for Custom Client

### ISSUE THREAD

**Issue by broxen** [Segs/Segs-Data#8]
## Summary
This is a Meta issue for tracking efforts to create or recreate assets for a future custom client. We're still a little ways off from being able to utilize anything, but we've received a large number of queries from members of the community looking to contribute this type of content. Because of that interest, I wanted to create this meta issue to track what we'll need and provide a place for those users to express their interest (where I wont lose it later =P)

## Assets We'll Need (in no particular order)
- [ ] Launcher and Login Background(s)
- [ ] Server and Client Selection Screen Backgrounds
- [ ] General UI elements for Launcher, Login, In Game UI Screens #6
- [ ] Icons for applications, icons for powers, inspirations, salvage, etc 
- [ ] Music for Launcher and Login/CharSel screens
- [ ] In-game music, for zones, missions, night club, etc.
- [ ] In-game sound effects for powers, movement, ambient noise
- [ ] Other stuff I'm forgetting.

## How to help!
If you're interested in creating or helping to create any of these assets, please post a reply to this Issue, and speak about what your skillset is and which assets you'd like to focus on. Then, if you're ready, feel free to dive in by creating mockups or samples of what you'd like to contribute. You can post those samples in a NEW issue specific to your goal, or if ready for real review, submit them to this github repo as a Pull Request.

As always, check in on the #art-and-assets channel on our discord with any questions.

**Comment by riellefrost** [comment]
Illustrator. Skillset is mostly 2D work (focus is character illustration & design, but can do environment, and UI graphics if needed), also some experience with 3D modeling and texture mapping/painting.

Some samples of my work:
https://pbs.twimg.com/media/DoejDW7W4AEVvWj.jpg
https://pbs.twimg.com/media/DdcgfhcVwAASGnp.jpg
https://pbs.twimg.com/media/DfxPm60UYAA4Fjc.png
https://pbs.twimg.com/media/DgfSoU8UYAAXRRQ.jpg
https://pbs.twimg.com/media/DhRooD1U8AACkdm.jpg
https://pbs.twimg.com/media/DiBIQzvUEAABF4r.jpg

**Comment by blackwingdesign** [comment]
Graphic designer, logo designer, illustrator, front end website designer.
https://www.facebook.com/blackwingdesignnet/
http://blackwingdesign.net/
